version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5757:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: ["node", "index.js"]